# Generated by Django 2.0 on 2019-05-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auto_20190510_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='跟进日期')),
                ('content', models.TextField(verbose_name='跟进内容')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='客户姓名')),
                ('contact', models.EmailField(max_length=128, verbose_name='联系方式')),
                ('status', models.IntegerField(choices=[(1, '已签合同'), (2, '未签合同')], verbose_name='状态')),
                ('source', models.IntegerField(choices=[(1, '已签合同'), (2, '未签合同')], verbose_name='销售渠道')),
                ('consultant_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(choices=[(1, '定金'), (2, '尾款'), (3, '其它')], default=1, verbose_name='付款类型')),
                ('paid_fee', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='费用')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='确认日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='生产流程名称')),
                ('status', models.IntegerField(choices=[(1, '未准备好'), (2, '已准备好')], default=2, verbose_name='生产流程状态')),
                ('reason', models.TextField(verbose_name='原因')),
                ('scedule', models.TextField(verbose_name='产品完成进度')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.procedure', verbose_name='上一个流程')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='产品价格')),
                ('paramters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '审核通过'), (2, '审核未通过')], default=1)),
                ('audit_date', models.DateField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.DepartMent', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='生产车间')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='工艺参数')),
                ('quality', models.TextField(blank=True, null=True, verbose_name='品质参数')),
            ],
        ),
        migrations.AddField(
            model_name='productaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WorkShop', verbose_name='生产车间'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='crm.UserInfo', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='所咨询客户'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(to='crm.Product', verbose_name='咨询的产品'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='crm.Customer', verbose_name='自己内部顾客介绍'),
        ),
        migrations.AddField(
            model_name='consultantrecord',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='consultantrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='所咨询客户'),
        ),
    ]
