# Generated by Django 2.0 on 2019-05-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, '已签合同'), (2, '未签合同')], default=2, verbose_name='状态'),
        ),
    ]
