# Generated by Django 2.0 on 2019-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190511_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.IntegerField(choices=[(1, '官方网站'), (2, '销售宣传'), (3, '代理商')], verbose_name='销售渠道'),
        ),
    ]
