# Generated by Django 2.0 on 2019-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190511_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(help_text='电话/微信等', max_length=32, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
    ]
