# Generated by Django 2.0 on 2019-05-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190511_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_fee',
            field=models.CharField(max_length=16, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=16, verbose_name='产品价格'),
        ),
    ]
