# Generated by Django 2.0 on 2019-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, '官方网站'), (2, '销售宣传'), (3, '代理商')], null=True, verbose_name='销售渠道'),
        ),
    ]
