# Generated by Django 2.0 on 2019-05-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190511_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'department__name': '项目部'}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'department__name': '财务部'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='crm.UserInfo', verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'department__name': '项目部'}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
    ]
