# Generated by Django 2.0 on 2019-05-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20190512_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='生产的产品'),
        ),
    ]
