# Generated by Django 2.0 on 2019-05-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20190512_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=16, verbose_name='车间'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品'),
        ),
    ]
