# Generated by Django 2.0 on 2019-05-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190512_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='reason',
            field=models.TextField(blank=True, help_text='如果该流程出现问题，请说明原因', null=True, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='scedule',
            field=models.TextField(blank=True, null=True, verbose_name='产品完成情况'),
        ),
    ]
