# Generated by Django 2.0 on 2019-05-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190512_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='product',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品名称'),
            preserve_default=False,
        ),
    ]
