# Generated by Django 2.0 on 2019-05-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20190512_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='工艺参数')),
                ('quality', models.TextField(blank=True, null=True, verbose_name='品质参数')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品')),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='technology',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='车间'),
        ),
        migrations.AddField(
            model_name='productparameter',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WorkShop', verbose_name='车间'),
        ),
    ]
