# Generated by Django 2.0 on 2019-05-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20190512_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '定金'), (2, '尾款'), (3, '其它')], default=0, verbose_name='付款类型'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
