# Generated by Django 2.0 on 2019-05-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20190512_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaudit',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='未通过原因'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
