# Generated by Django 2.0 on 2019-05-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20190512_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='audit_date',
            field=models.DateField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='status',
            field=models.IntegerField(choices=[(1, '审核通过'), (2, '审核未通过')], verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='user',
            field=models.ForeignKey(limit_choices_to={'department__name': '总经理办'}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='审核人'),
        ),
    ]
