# Generated by Django 2.0 on 2019-05-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20190512_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='product_status',
            field=models.IntegerField(default=1, verbose_name='产品完成状态'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
