# Generated by Django 2.0 on 2019-05-13 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20190512_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='产品数量')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('consultant', models.ForeignKey(blank=True, limit_choices_to={'department__name': '项目部'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='购买的产品')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='customer',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='订单'),
        ),
    ]
