# Generated by Django 2.0 on 2019-05-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20190513_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='跟进日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='确认日期'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
