# Generated by Django 2.0 on 2019-05-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20190514_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
