# Generated by Django 2.0 on 2019-05-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_auto_20190515_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='订单审核'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
