# Generated by Django 2.0 on 2019-05-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20190516_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='product',
        ),
        migrations.AddField(
            model_name='procedure',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
