# Generated by Django 2.0 on 2019-05-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20190517_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='audit_status',
            field=models.IntegerField(choices=[(1, '未完成'), (2, '已完成')], default=1, verbose_name='产品审核状态'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程'),
        ),
    ]
